package n_17.n_4;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        throw new IOException("例外が発生しました");
    }
}
